### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [RedFoxFinn/rff-project#32]
# Katselmointi

Terve @RedFoxFinn! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Rekisteröin uuden käyttäjän ja kirjauduin sisään
- Testailin Calculate-sovellusta
- Testailin OpenCountry-sovellusta
- Testailin Dishy-sovellusta
- Testailin Tasker-sovellusta
- Kirjauduin ulos

### Kokemus

- Selkeä käyttöliittymä, dark/light-teemavalinnoista plussaa. Hyvää työtä! 🥇
- Calculate-sovelluksessa negatiivisen luvun neliöjuureksi tulee `NaN`
- Dishy-sovelluksessa "Save dish"-napin painaminen ei tunnu tallentevan annosta eikä käyttöliittymässä näy mitään virheilmoitusta

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- react-routerin `Route`-komponentin antamia propseja ei tarvitse siirtää lapsille, vaan routerin tilan saa tarvittaessa react-routerin tarjoamilla [hookseilla](https://reacttraining.com/react-router/web/api/Hooks): https://github.com/RedFoxFinn/rff-project/blob/frontend/src/App.js#L134
- Älä määrittele React-komponentteja renderöinnin aikana, vaan siirrä ne renderöinti-fuktion ulkopuolelle: https://github.com/RedFoxFinn/rff-project/blob/frontend/src/App.js#L151
- Apollo-clienttien konfiguroinnit voisi siirtää muualle: https://github.com/RedFoxFinn/rff-project/blob/frontend/src/App.js#L151
- Maatiedot kannattaisi hakea "laiskasti", eli vasta kun niitä tarvitaan: https://github.com/RedFoxFinn/rff-project/blob/frontend/src/App.js#L104
- Redux actioneiden tyypit kannattaa tallentaa const-muuttujiin typojen välttämiseksi ja refaktroinnin helpottamiseksi. Jos reducereita on monta kannattaa prefiksata tyypin nimi reducerin nimellä, esim:

```javascript
const SET_CARB_SEARCH = 'dishy/setCarbSearch';

// ...

const DishyReducer = (state = initialState, action) => {
  switch (action.type) {
    case SET_CARB_SEARCH:
    // ...
  }
};
```

- Globaalit tyylit voisi importata jo `index.js`-tiedostossa: https://github.com/RedFoxFinn/rff-project/blob/frontend/src/components/Calculate.js#L10
- Tyylejä kannattaa eritellä niitä käyttävien komponenttien mukaan esim. omiksi kansiomoduuleikseen:

```
Dishy/
  - index.jsx
  - style.css
```

Tyylien luokkien nimissä voi käyttää komponentin nimeä etuliitteenä, esim. `.Dishy__dishList` ja `.Dishy__dishListItem`. Tämä vähentää riskiä luokkien nimien yhteentörmäyksessä. Modernimpi ratkaisu tähän ongelmaan on [css-moduulit](https://github.com/css-modules/css-modules).
- Lomakkeiden tilanhallinta on hoidettu melko siististi, mutta kun lomakkeen koko kasvaa tai sen logiikka monimutkaistuu, on usein kätevää käyttää jotain lomakkeen tilanhallinnan hoitavaa kirjastoa, kuten [Formik](https://jaredpalmer.com/formik)

- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- GraphQL-apin resolvereita ja tyyppimäärityksiä kannattaisi eritellä, ettei kaikki olisi samassa tiedostossa. Tässä yksi esimerkki, miten tämän voisi organisoida: https://github.com/Kaltsoon/rate-repository-api/tree/master/src/graphql

## Kokonaisuus

- Hyvä kokoelma pieniä eri käyttötarkoitukseen soveltuvia sovelluksia
- Koodi on kaikin puolin hyvin organisoitua ja melko laadukasta, mutta myös refaktoroitavaa löytyy

**Comment by RedFoxFinn** [comment]
> # Katselmointi
> Terve @RedFoxFinn! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.
> 
> ## Käytettävyys
> ### Mitä tein?
> * Rekisteröin uuden käyttäjän ja kirjauduin sisään
> * Testailin Calculate-sovellusta
> * Testailin OpenCountry-sovellusta
> * Testailin Dishy-sovellusta
> * Testailin Tasker-sovellusta
> * Kirjauduin ulos
> 
> ### Kokemus
> * Selkeä käyttöliittymä, dark/light-teemavalinnoista plussaa. Hyvää työtä! 1st_place_medal
> * Calculate-sovelluksessa negatiivisen luvun neliöjuureksi tulee `NaN`
> * Dishy-sovelluksessa "Save dish"-napin painaminen ei tunnu tallentevan annosta eikä käyttöliittymässä näy mitään virheilmoitusta
> 
> ## Koodi
> * Frontend-puolen koodi on selkeästi organisoitua, hyvä!
> * react-routerin `Route`-komponentin antamia propseja ei tarvitse siirtää lapsille, vaan routerin tilan saa tarvittaessa react-routerin tarjoamilla [hookseilla](https://reacttraining.com/react-router/web/api/Hooks): https://github.com/RedFoxFinn/rff-project/blob/frontend/src/App.js#L134
> * Älä määrittele React-komponentteja renderöinnin aikana, vaan siirrä ne renderöinti-fuktion ulkopuolelle: https://github.com/RedFoxFinn/rff-project/blob/frontend/src/App.js#L151
> * Apollo-clienttien konfiguroinnit voisi siirtää muualle: https://github.com/RedFoxFinn/rff-project/blob/frontend/src/App.js#L151
> * Maatiedot kannattaisi hakea "laiskasti", eli vasta kun niitä tarvitaan: https://github.com/RedFoxFinn/rff-project/blob/frontend/src/App.js#L104
> * Redux actioneiden tyypit kannattaa tallentaa const-muuttujiin typojen välttämiseksi ja refaktroinnin helpottamiseksi. Jos reducereita on monta kannattaa prefiksata tyypin nimi reducerin nimellä, esim:
> 
> ```js
> const SET_CARB_SEARCH = 'dishy/setCarbSearch';
> 
> // ...
> 
> const DishyReducer = (state = initialState, action) => {
>   switch (action.type) {
>     case SET_CARB_SEARCH:
>     // ...
>   }
> };
> ```
> 
> * Globaalit tyylit voisi importata jo `index.js`-tiedostossa: https://github.com/RedFoxFinn/rff-project/blob/frontend/src/components/Calculate.js#L10
> * Tyylejä kannattaa eritellä niitä käyttävien komponenttien mukaan esim. omiksi kansiomoduuleikseen:
> 
> ```
> Dishy/
>   - index.jsx
>   - style.css
> ```
> 
> Tyylien luokkien nimissä voi käyttää komponentin nimeä etuliitteenä, esim. `.Dishy__dishList` ja `.Dishy__dishListItem`. Tämä vähentää riskiä luokkien nimien yhteentörmäyksessä. Modernimpi ratkaisu tähän ongelmaan on [css-moduulit](https://github.com/css-modules/css-modules).
> 
> * Lomakkeiden tilanhallinta on hoidettu melko siististi, mutta kun lomakkeen koko kasvaa tai sen logiikka monimutkaistuu, on usein kätevää käyttää jotain lomakkeen tilanhallinnan hoitavaa kirjastoa, kuten [Formik](https://jaredpalmer.com/formik)
> * Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
> * GraphQL-apin resolvereita ja tyyppimäärityksiä kannattaisi eritellä, ettei kaikki olisi samassa tiedostossa. Tässä yksi esimerkki, miten tämän voisi organisoida: https://github.com/Kaltsoon/rate-repository-api/tree/master/src/graphql
> 
> ## Kokonaisuus
> * Hyvä kokoelma pieniä eri käyttötarkoitukseen soveltuvia sovelluksia
> * Koodi on kaikin puolin hyvin organisoitua ja melko laadukasta, mutta myös refaktoroitavaa löytyy

Kiitoksia kommenteista ja vinkeistä, otan näitä huomioon jatkokehityksessä :)
